name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted, macOS, X64, affan-local-machine]
    steps:
      - run: echo "Hello World"
