name: rollback-for-local-machines
run-name: rollback-for-local-machines
on:
  push:
    branches:
      - local-machines-rollback
jobs:
  affan-local-machine-rollback-job:
    runs-on: [self-hosted, macOS, X64, affan-local-machine]
    steps:
      - run: cd ~/self-runner-deployment-poc/ && git fetch origin local-machines && git checkout local-machines && git pull origin local-machines && chmod +x ./rollback-script && ./rollback-script ahassan
  danish-local-machine-rollback-job:
    runs-on: [self-hosted, macOS, X64, danish-local-machine]
    steps:
      - run: cd ~/self-runner-deployment-poc/ && git fetch origin local-machines && git checkout local-machines && git pull origin local-machines && chmod +x ./rollback-script && ./rollback-script mdanish
